os: linux
dist: xenial
language: python
python: "3.7"
services:
  - docker
env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
install:
  - pip install conan --upgrade
  - pip install conan_package_tools
before_script:
  - conan user
script:
  - python build.py
